export const EMAIL_DOMAIN = [
  'naver.com',
  'nate.com',
  'kakao.com',
  'gmail.com',
  'daum.net',
  'outlook.com',
  'korea.kr',
  'hanmail.com',
  'outlook.kr',
  'outlook.com',
  'hotmail.com',
  'yahoo.com',
  'mango.com',
  'mangolove.com',
];
