spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: w3cJhS2ijZuO0EaVOqj4
            client-secret: 5XY7cpRsj0
            scope: email
            name: never
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

            authorization-uri: https://nid.naver.com/oauth2.0/authorize #
            token-uri: https://nid.naver.com/oauth2.0/token #
            user-info-uri: https://openapi.naver.com/v1/nid/me #
            user-name-attribute: response #

          kakao:
            client-id: d2c191a8ffec18a46c5dbd45bd93d36a # ${KAKAO_REST_API_KEY}
            client-secret: #
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: kakao
            client-authentication-method: POST

            ## KAKAO Provider
            authorization-uri: https://kauth.kakao.com/oauth/authorize #
            token-uri: https://kauth.kakao.com/oauth/token #
            user-info-uri: https://kapi.kakao.com/v2/user/me #
            user-name-attribute: id


          google:
            clientId: 169242830549-appje0sp82r5s1l19bglnsonk40dv7u0.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
#mail:
#  address:
#    admin: admin@gmail.com
jwt:
  key: neverland123123123123123123123123123123 # 환경변수 ${JWT_KEY}
  access-token-expiration-minutes: 60          # 환경변수 ${JWT_ACCESS_TOKEN}
  refresh-token-expiration-minutes: 10080      # 환경변수 ${JWT_REFRESH_TOKEN}