spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:mysql://db-zerohip.coprrm1yhque.ap-northeast-2.rds.amazonaws.com:3306/zerohip?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: admin
    password: zerohip016
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
#mail:
#  address:
#    admin: admin@gmail.com
jwt:
  key: neverland123123123123123123123123123123 # 배포 전 환경변수 포맷 후 ec2 인스턴스에 변수 등록
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420