spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 169242830549-appje0sp82r5s1l19bglnsonk40dv7u0.apps.googleusercontent.com  # 환경변수 ${GOOGLE_CLIENT_ID}
            clientSecret: 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  # 환경변수 ${GOOGLE_CLIENT_SECRET}
#mail:
#  address:
#    admin: admin@gmail.com
jwt:
  key: neverland123123123123123123123123123123 # 환경변수 ${JWT_KEY}
  access-token-expiration-minutes: 60          # 환경변수 ${JWT_ACCESS_TOKEN}
  refresh-token-expiration-minutes: 10080      # 환경변수 ${JWT_REFRESH_TOKEN}