spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
#mail:
#  address:
#    admin: admin@gmail.com
jwt:
  key: neverland123123123123123123123123123123 # 환경변수 ${JWT_KEY}
  access-token-expiration-minutes: 60          # 환경변수 ${JWT_ACCESS_TOKEN}
  refresh-token-expiration-minutes: 10080      # 환경변수 ${JWT_REFRESH_TOKEN}